name: Continuous Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Firebase hosting
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          version: 12
          runtime: node@lts
          cache: true

      - name: Astro build
        run: pnpm build

      - name: Storybook build
        run: pnpm build-storybook

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_APHRODITE_CHIBI }}
          projectId: chibi-ui
          channelId: live
